version: '3.8'

services:
  mariadb:
    image: mariadb:awaken
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    expose:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h127.0.0.1", "-uroot", "-p${SQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:awaken
    build:
      context: ./requirements/nginx
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    restart: always

  wordpress:
    image: wordpress:awaken
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - 9000
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    restart: always 

  ftp:
    image: ftp:awaken
    build:
      context: ./requirements/bonus/ftp
    container_name: ftp
    networks:
      - inception
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - wordpress:/home/$FTP_USER/ftp/wordpress
    env_file: .env

  website:
    image: website:awaken
    build:
      context: ./requirements/bonus/website
    container_name: website
    networks:
      - inception
    ports:
      - "1337:1337"
    restart: always

  cadvisor:
    image: cadvisor:awaken
    build:
      context: ./requirements/bonus/cadvisor
    container_name: cadvisor
    networks:
      - inception
    ports:
      - "8080:8080"
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: always

  adminer:
    image: adminer:awaken
    build:
      context: ./requirements/bonus/adminer
    container_name: adminer
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "600:80"
    restart: always

  redis:
    image: redis:awaken
    build:
      context: ./requirements/bonus/redis
    container_name: redis
    networks:
      - inception
    expose:
      - 6379
    restart: always
    depends_on:
      - wordpress
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bel-oirg/data/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/bel-oirg/data/mariadb'

networks:
  inception:
    driver: bridge
